### ISSUE TITLE
As a user, the QT gui remains open, so that I can use the program more easily.

### ISSUE THREAD

**Issue by at527** [ucsb-cs148-s21/t7-local-network-file-transfer#21]
## Acceptance Criteria
- [x] A QT window is open
- [x] The app does not freeze when the server is started (buttons can be toggled)
- [x] All members have tested to make sure that the threading works on their machine.

## Front End (host machine)
- [x] QT window remains open

## Backend
- [x] Run QT in separate process/thread

**Comment by ethwu** [comment]
Resolved by #27
